### ISSUE TITLE
Error when attempting to connect to API endpoint 'incidents'

### ISSUE THREAD

**Issue by weslambert** [byt3smith/fir-powershell#1]
Please forgive me if I should raise a question in another manner, but I was attempting to use the script, and while doing so, I continue to receive the following error:

`System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.`

I run the script as follows:

powershell -File fir-client.ps1 -u https://fir-host.com -t <token> -ep incidents

I have ensured the firewall rules allow the desired traffic, and can manually navigate to each endpoint (in the browser), but for some reason, when I run the script, I get the above error.

Thoughts?  Any assistance would be greatly appreciated.

Thanks,
Wes

**Comment by weslambert** [comment]
This was resolved by specifying the use of TLSv1.2 for the connection (referenced in the PR above).

Thanks,
Wes

**Comment by burdenless** [comment]
Cool. Also, this is the best place for raising questions/concerns, feature requests, etc. So feel free

**Comment by weslambert** [comment]
Thanks!

I have been able to successfully use the client to insert a user, but am
still working on how to insert an incident.

I've posting how I am currently trying to add an incident here:

https://groups.google.com/forum/#!topic/fir-users/nM-AmlJzcLw

Would you be able to provide any advice?  I know this is more so
API-related and not client-related, but this is really grinding my gears :)

Thanks,

Wes

**Comment by burdenless** [comment]
@weslambert have you tried looking at the API documentation generated on your FIR instance at the API root?

It is located at https://$FIR_INSTANCE**/api**

It will look something like this, and shows you all of the fields that need to be present in the JSON body that you pass in.

<img width="846" alt="screen shot 2016-09-09 at 3 05 50 pm" src="https://cloud.githubusercontent.com/assets/6267544/18404328/d3451a98-769e-11e6-9688-50fd6c2954a3.png">

That may be helpful to you until we can get full documentation completed.

**Comment by weslambert** [comment]
Yeah, I had a look and (aside from the post in the link) tried passing in
all the fields show using a Powershell hashtable, which worked for users,
but not incidents. :(

**Comment by burdenless** [comment]
Well, I should have some time this weekend, I'll get some POST examples working with the PS client

**Comment by weslambert** [comment]
Thank you!  I REALLY appreciate it.
